### ISSUE TITLE
Hi, I want to ask when the codes and model for ReID  will be released?

### ISSUE THREAD

**Issue by ZikunZhou** [hqucv/dmtrack#5]

**Comment by lyfQAQ** [comment]
> _未提供说明。_



> 



> _No description provided._

请问，这里面有没有re_id部分?

**Comment by ZikunZhou** [comment]
Hi, I do not find the codes for re-id.




Best wishes!
Zikun
***@***.***
On 4/15/2022 ***@***.***> wrote：

未提供说明。

No description provided.

请问，这里面有没有re_id部分?
